name: update-layui-layer

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ master ]

jobs:
  update-html-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # install deps
      - run: npm i -g pnpm
      - run: pnpm i

      # update data
      - name: Update Layui Layer
        run: npm run update
      
      # Build
      - name: Build
        run: npm run build

      # commit
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "ci(layer): update layui layer"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
